name: insert notion db batch

on: # push
  schedule:
    - cron: "0 19 * * *" # 実行したい時間を指定(時間がutcなので注意)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch #作業ブランチにchekout
        uses: actions/checkout@v2 #サードパーティの公開アクションを利用
        with:
          ref: ${{ github.ref }}
      - name: Git setting
        run: |
          # pullしておかないと Re-run all jobs 実行時はコケてしまうため
          git pull
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit and push
        run: |
          git commit --allow-empty -m "chore: prevent automatic workflow stopping" -m "see: https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow"
          git push
      - name: batch
        env:
          ENCODED_ENV: ${{ secrets.ENCODED_ENV }}
        run: |
          echo "insert notion batch start" 
          echo -n ${ENCODED_ENV} | base64 -d > .env
          docker compose run zenn_qiita python insert_notion.py
          echo "insert notion batch end"
      - name: success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          description: "TechSite Trend Insert NotionDB Batch Success!!"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      - name: failure
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: "TechSite Trend Insert NotionDB Batch Failure!!"
          color: 0xff91a4
